### ISSUE TITLE
Epic of big features

### ISSUE THREAD

**Issue by kipply** [the-template-project/root#1]
- [ ] Have a carousel panel for each template
 - [ ] Add a small info section at the top about the project
 - [ ] add a download button for each template
 - [ ] Live preview button for each template 
 - [ ] have the templates show up in a random order on each visit!
